force-app/main/default/objects/Talent__c/Talent__c.object-meta.xml
<CustomObject>
    <label>Talent</label>
    <nameField>
        <displayFormat>TN-{00000}</displayFormat>
        <label>Talent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Talents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Talent__c/fields/Interview_Result__c.field-meta.xml
<CustomField>
    <fullName>Interview_Result__c</fullName>
    <label>Interview Result</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InterviewResourceTest.cls
@isTest
public class InterviewResourceTest {
  @IsTest
  static void testUpdateInterviewResultSuccessfully() {
    RestContext.request = new RestRequest();
    RestContext.request.requestBody = Blob.valueof(
      '{"interviewResults":[{"id":"a025i000006XOzvAAG","interviewResult":"fail","interviewDate":"2022-07-21 00:00:00"}]}'
    );

    Test.startTest();
    List<ResponseResult> responses = InterviewResource.syncInterviewResult();
    Test.stopTest();

    Talent__c updatedTalent = [
      SELECT Interview_Result__c, Interview_Date__c
      FROM Talent__c
    ];
    System.assertEquals('fail', updatedTalent.Interview_Result__c);
    System.assertEquals(
      Date.valueOf('2022-07-21 00:00:0'),
      updatedTalent.Interview_Date__c
    );
    System.assertEquals('Successful', responses[0].status);
    System.assertEquals('200', responses[0].statusCode);
    System.assertEquals(
      'Interview results of talent a025i000006XOzvAAG are updated successfully.',
      responses[0].statusMsg
    );
  }

  @IsTest
  static void testUpdateInterviewResultFailed() {
    RestContext.request = new RestRequest();
    RestContext.request.requestBody = Blob.valueof(
      '{"interviewResults":[{"id":"a025i000006XOzvAAA","interviewResult":"fail","interviewDate":"2022-07-21 00:00:00"}]}'
    );

    Test.startTest();
    List<ResponseResult> responses = InterviewResource.syncInterviewResult();
    Test.stopTest();

    System.assertEquals('Failed', responses[0].status);
    System.assertEquals('400', responses[0].statusCode);
    System.assertEquals(
      'Interview results of talent a025i000006XOzvAAA are updated failed.',
      responses[0].statusMsg
    );
  }
}