force-app/main/default/objects/Log__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <label>StatusCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Talent__c/Talent__c.object-meta.xml
<CustomObject>
    <label>Talent</label>
    <nameField>
        <displayFormat>TN-{00000}</displayFormat>
        <label>Talent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Talents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Talent__c/fields/Interview_Result__c.field-meta.xml
<CustomField>
    <fullName>Interview_Result__c</fullName>
    <label>Interview Result</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Talent__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Log</label>
    <referenceTo>Log__c</referenceTo>
    <relationshipLabel>Talents</relationshipLabel>
    <relationshipName>Talents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Talent__c/fields/Skill_Set__c.field-meta.xml
<CustomField>
    <fullName>Skill_Set__c</fullName>
    <label>Skill Set</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>Python</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/talentTest.cls
@isTest
public class talentTest {
  @TestSetup
  static void makeData() {
    Talent__c talent = new Talent__c(Skill_Set__c = 'Python');
    insert talent;
  }

  @isTest
  static void syncNewTalentSuccessful() {
    Test.setMock(HttpCalloutMock.class, new TalentHttpCalloutMock());

    Talent__c newTalent = new Talent__c(
      Skill_Set__c = 'Salesforce;English;Python'
    );
    Test.startTest();
    insert newTalent;
    Test.stopTest();

    Log__c syncLog = [SELECT StatusCode__c, Status__c, Message__c FROM Log__c];
    System.assertEquals('200', syncLog.StatusCode__c);
    System.assertEquals('Success', syncLog.Status__c);
    System.assertEquals(
      '候选人信息已经录入, 感谢您对Thoughtworks招聘的支持!',
      syncLog.Message__c
    );
  }

  @isTest
  static void syncUpdatedTalentSuccessful() {
    Test.setMock(HttpCalloutMock.class, new TalentHttpCalloutMock());

    Talent__c updatedTalent = [SELECT Id FROM Talent__c];
    updatedTalent.Skill_Set__c = 'Salesforce;English;Python';
    Test.startTest();
    update updatedTalent;
    Test.stopTest();

    Log__c syncLog = [SELECT StatusCode__c, Status__c, Message__c FROM Log__c];
    System.assertEquals('200', syncLog.StatusCode__c);
    System.assertEquals('Success', syncLog.Status__c);
    System.assertEquals(
      '候选人信息已经录入, 感谢您对Thoughtworks招聘的支持!',
      syncLog.Message__c
    );
  }

  @isTest
  static void doNotSyncNewTalentWithoutRequiredSkill() {
    Test.setMock(HttpCalloutMock.class, new TalentHttpCalloutMock());

    Talent__c newTalent = new Talent__c(Skill_Set__c = 'Salesforce;Python');
    Test.startTest();
    insert newTalent;
    Test.stopTest();

    List<Log__c> syncLog = [
      SELECT StatusCode__c, Status__c, Message__c
      FROM Log__c
    ];
    System.assertEquals(true, syncLog.isEmpty());
  }

  @isTest
  static void doNotSyncUpdatedTalentWithoutRequiredSkill() {
    Talent__c updatedTalent = [SELECT Id FROM Talent__c];
    updatedTalent.Skill_Set__c = 'English;Python';
    Test.startTest();
    update updatedTalent;
    Test.stopTest();

    List<Log__c> syncLog = [
      SELECT StatusCode__c, Status__c, Message__c
      FROM Log__c
    ];
    System.assertEquals(true, syncLog.isEmpty());
  }

  @isTest
  static void doNotSyncUpdatedTalentWithFailedInterview() {
    Talent__c updatedTalent = [SELECT Id FROM Talent__c];
    updatedTalent.Skill_Set__c = 'Salesforce;English;Python';
    updatedTalent.Interview_Result__c = 'Fail';
    Test.startTest();
    update updatedTalent;
    Test.stopTest();

    List<Log__c> syncLog = [
      SELECT StatusCode__c, Status__c, Message__c
      FROM Log__c
    ];
    System.assertEquals(true, syncLog.isEmpty());
  }
}